name: Tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
            plone-version: '5.2'
          - python-version: '3.12'
            plone-version: '6.0'

    steps:
      # git checkout
      - uses: actions/checkout@v4

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # buildout eggs cache
      - uses: actions/cache@v4
        with:
          path: eggs
          key: ${{ runner.os }}-py${{ matrix.python-version }}-plone${{ matrix.plone-version }}-${{ hashFiles('*.cfg') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-plone${{ matrix.plone-version }}-
            ${{ runner.os }}-py${{ matrix.python-version }}-

      # python install
      - name: pip install
        run: pip install -r requirements-${{ matrix.plone-version }}.txt

      # buildout
      - name: buildout
        run: buildout -t 10 -c plone-${{ matrix.plone-version }}.x.cfg
        env:
          CI: true

      # test
      - name: test
        run: bin/test
